# Generated by Django 5.2.1 on 2025-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': 'College'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name_plural': 'Register'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.RenameField(
            model_name='register',
            old_name='Firstname',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='Lastname',
        ),
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(default='', upload_to='media/profile_photos'),
        ),
        migrations.AddField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='lastname',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
