# Generated by Django 5.2.1 on 2025-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_register_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='lastname',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(upload_to='profile_photos'),
        ),
    ]
