# Generated by Django 5.2.1 on 2025-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
    ]
