# Generated by Django 5.2.1 on 2025-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_register_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
